apiVersion: v1
kind: Service
metadata:
  name: {{ include "tape.fullname" . }}-entry
  labels:
    {{- include "tape.labels" . | nindent 4 }}
    app.kubernetes.io/component: entry
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.entry.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "tape.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: entry
