#!/usr/bin/env node
// api-report — public API surface reports for the published tape libraries.
//
// Reads the tsup-rolled-up .d.ts files from each library's dist/, normalizes
// them, and writes docs/api/<pkg>.api.md. CI runs `pnpm api-report:check`,
// so any PR that changes a public surface necessarily shows a diff under
// docs/api/ — API changes are visible at review time, never accidental.
//
// Zero dependencies: node:fs and node:path only.
//
//   node tools/api-report.mjs           regenerate docs/api/*.api.md
//   node tools/api-report.mjs --check   verify committed reports match dist/

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = dirname(dirname(fileURLToPath(import.meta.url)));

const TARGETS = [
  {
    pkgDir: 'packages/tape-core',
    declarations: ['dist/index.d.ts', 'dist/protocol.d.ts'],
    report: 'docs/api/tape-core.api.md',
  },
  {
    pkgDir: 'packages/tape-react',
    declarations: ['dist/index.d.ts'],
    report: 'docs/api/tape-react.api.md',
  },
];

/** Strip sourceMappingURL comments and trailing whitespace; normalize EOF. */
function normalize(dts) {
  return (
    dts
      .split('\n')
      .filter((line) => !/^\s*\/\/#\s*sourceMappingURL=/.test(line))
      .map((line) => line.replace(/\s+$/, ''))
      .join('\n')
      .replace(/\n+$/, '') + '\n'
  );
}

function generate(target) {
  const pkgJsonPath = join(repoRoot, target.pkgDir, 'package.json');
  const pkg = JSON.parse(readFileSync(pkgJsonPath, 'utf8'));

  const sections = target.declarations.map((rel) => {
    const abs = join(repoRoot, target.pkgDir, rel);
    if (!existsSync(abs)) {
      console.error(
        `api-report: missing ${target.pkgDir}/${rel} — build the libraries first: pnpm -r build`
      );
      process.exit(1);
    }
    return `### \`${rel}\`\n\n\`\`\`ts\n${normalize(readFileSync(abs, 'utf8'))}\`\`\`\n`;
  });

  return (
    `# API surface: ${pkg.name}\n\n` +
    `Version: ${pkg.version}\n\n` +
    `Generated by \`pnpm api-report\` — do not edit; CI fails if this drifts from the built declarations.\n\n` +
    sections.join('\n')
  );
}

const check = process.argv.includes('--check');
let drifted = 0;

for (const target of TARGETS) {
  const content = generate(target);
  const reportPath = join(repoRoot, target.report);

  if (check) {
    const committed = existsSync(reportPath) ? readFileSync(reportPath, 'utf8') : null;
    if (committed === null) {
      console.error(`api-report: ${target.report} is missing — run: pnpm api-report`);
      drifted++;
    } else if (!Buffer.from(committed, 'utf8').equals(Buffer.from(content, 'utf8'))) {
      console.error(
        `api-report: ${target.report} drifted from the built declarations — run: pnpm api-report (then commit the diff)`
      );
      drifted++;
    } else {
      console.log(`api-report: ${target.report} matches dist`);
    }
  } else {
    mkdirSync(dirname(reportPath), { recursive: true });
    writeFileSync(reportPath, content);
    console.log(`api-report: wrote ${relative(repoRoot, reportPath)}`);
  }
}

if (check && drifted > 0) process.exit(1);
